# Generated by Django 5.0.4 on 2024-05-04 17:32

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(help_text='Введите описание категории', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название цвета', max_length=100, verbose_name='Название цвета')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название сети', max_length=100, verbose_name='Название сети')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Сеть',
                'verbose_name_plural': 'Сети',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите изображение', upload_to='phones', verbose_name='')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='phones.color')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(help_text='Введите название телефона', max_length=100, verbose_name='Название')),
                ('main_info', ckeditor.fields.RichTextField(help_text='Введите основную информацию о телефоне', verbose_name='Основная информация')),
                ('characteristics', ckeditor.fields.RichTextField(help_text='Введите характеристики телефона', verbose_name='Характеристики')),
                ('camera_info', ckeditor.fields.RichTextField(help_text='Введите информацию о камере', verbose_name='Камера')),
                ('sensors', ckeditor.fields.RichTextField(help_text='Введите информацию о датчиках', verbose_name='Датчики')),
                ('kit_info', ckeditor.fields.RichTextField(help_text='Введите информацию о комплекте поставки', verbose_name='Комплект поставки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='phones.category')),
                ('network', models.ManyToManyField(related_name='phones', to='phones.network')),
                ('photos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='phones.photo')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
    ]
