# Generated by Django 5.0.4 on 2024-05-04 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='photos',
        ),
        migrations.AddField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('draft', 'Не активен'), ('published', 'Активен')], default='draft', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='photo',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='phones.phone'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание категории', verbose_name='Описание'),
        ),
    ]
