# Generated by Django 5.0.4 on 2024-05-10 11:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_remove_phone_photos_phone_status_photo_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('preview_image', models.ImageField(help_text='Загрузите изображение', upload_to='newspapers', verbose_name='Превью')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('content', ckeditor.fields.RichTextField(help_text='Введите контент', verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
    ]
