# Generated by Django 5.0.4 on 2024-05-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('draft', 'Не активен'), ('published', 'Активен')], default='draft', max_length=10, verbose_name='Статус'),
        ),
    ]
