# Generated by Django 5.0.4 on 2024-05-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_news_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(help_text='Загрузите изображение', upload_to='phones'),
        ),
    ]
