# Generated by Django 5.0.4 on 2024-05-11 07:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_kk',
            field=ckeditor.fields.RichTextField(help_text='Введите контент', null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=ckeditor.fields.RichTextField(help_text='Введите контент', null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='phone',
            name='camera_info_kk',
            field=ckeditor.fields.RichTextField(help_text='Введите информацию о камере', null=True, verbose_name='Камера'),
        ),
        migrations.AddField(
            model_name='phone',
            name='camera_info_ru',
            field=ckeditor.fields.RichTextField(help_text='Введите информацию о камере', null=True, verbose_name='Камера'),
        ),
        migrations.AddField(
            model_name='phone',
            name='characteristics_kk',
            field=ckeditor.fields.RichTextField(help_text='Введите характеристики телефона', null=True, verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='phone',
            name='characteristics_ru',
            field=ckeditor.fields.RichTextField(help_text='Введите характеристики телефона', null=True, verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='phone',
            name='kit_info_kk',
            field=ckeditor.fields.RichTextField(help_text='Введите информацию о комплекте поставки', null=True, verbose_name='Комплект поставки'),
        ),
        migrations.AddField(
            model_name='phone',
            name='kit_info_ru',
            field=ckeditor.fields.RichTextField(help_text='Введите информацию о комплекте поставки', null=True, verbose_name='Комплект поставки'),
        ),
        migrations.AddField(
            model_name='phone',
            name='sensors_kk',
            field=ckeditor.fields.RichTextField(help_text='Введите информацию о датчиках', null=True, verbose_name='Датчики'),
        ),
        migrations.AddField(
            model_name='phone',
            name='sensors_ru',
            field=ckeditor.fields.RichTextField(help_text='Введите информацию о датчиках', null=True, verbose_name='Датчики'),
        ),
        migrations.AddField(
            model_name='phone',
            name='title_kk',
            field=models.CharField(help_text='Введите название телефона', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='phone',
            name='title_ru',
            field=models.CharField(help_text='Введите название телефона', max_length=100, null=True, verbose_name='Название'),
        ),
    ]
