# Generated by Django 5.0.4 on 2024-05-11 07:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_news_content_kk_news_content_ru_news_description_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='main_info_kk',
            field=ckeditor.fields.RichTextField(help_text='Введите основную информацию о телефоне', null=True, verbose_name='Основная информация'),
        ),
        migrations.AddField(
            model_name='phone',
            name='main_info_ru',
            field=ckeditor.fields.RichTextField(help_text='Введите основную информацию о телефоне', null=True, verbose_name='Основная информация'),
        ),
    ]
