# Generated by Django 5.0.4 on 2024-05-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0008_alter_news_managers_alter_phone_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('slider_news', 'На слайдере'), ('second_form_news', 'На второй форме')], default='second_form_news', max_length=20, verbose_name='Тип'),
        ),
    ]
