# Generated by Django 5.0.4 on 2024-05-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0009_news_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='type',
            new_name='pattern',
        ),
    ]
