# Generated by Django 5.0.4 on 2024-05-15 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0010_rename_type_news_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(help_text='Введите емкость батареи', verbose_name='Емкость')),
            ],
            options={
                'verbose_name': 'Батарея',
                'verbose_name_plural': 'Батареи',
            },
        ),
        migrations.CreateModel(
            name='CameraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('megapixels', models.PositiveIntegerField(help_text='Введите количество мегапикселей', verbose_name='Мегапиксели')),
            ],
            options={
                'verbose_name': 'Мегапиксель',
                'verbose_name_plural': 'Мегапиксели',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(help_text='Введите объем памяти', verbose_name='Объем памяти')),
            ],
            options={
                'verbose_name': 'Память',
                'verbose_name_plural': 'Память',
            },
        ),
        migrations.AddField(
            model_name='phone',
            name='display',
            field=models.FloatField(choices=[(5.0, '5,6"'), (5.5, '5,5"'), (5.65, '5,65"'), (5.7, '5,7"'), (6.0, '6"'), (6.1, '6,1"'), (6.2, '6,2"'), (6.35, '6,35"'), (6.4, '6,4"')], default=5.0, help_text='Выберите диагональ дисплея', verbose_name='Дисплей'),
        ),
        migrations.AddField(
            model_name='phone',
            name='has_touch_id',
            field=models.BooleanField(default=False, verbose_name='Есть Touch ID'),
        ),
        migrations.AddField(
            model_name='phone',
            name='resolution',
            field=models.CharField(choices=[('FHD', 'FHD'), ('HD', 'HD'), ('FWVGA', 'FWVGA'), ('WVGA', 'WVGA')], default='HD', help_text='Выберите разрешение экрана', max_length=10, verbose_name='Разрешение'),
        ),
        migrations.AddField(
            model_name='phone',
            name='battery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='phones.battery'),
        ),
        migrations.AddField(
            model_name='phone',
            name='back_camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_camera', to='phones.camerainfo'),
        ),
        migrations.AddField(
            model_name='phone',
            name='front_camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='front_camera', to='phones.camerainfo'),
        ),
        migrations.AddField(
            model_name='phone',
            name='memories',
            field=models.ManyToManyField(related_name='phones', to='phones.memory'),
        ),
    ]
