# Generated by Django 5.0.4 on 2024-05-24 05:51

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0012_alter_phone_battery_delete_battery'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='inner_link',
            field=models.URLField(blank=True, verbose_name='Ссылка (если имеется)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Введите контент', verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_kk',
            field=ckeditor.fields.RichTextField(help_text='Введите контент', null=True, verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=ckeditor.fields.RichTextField(help_text='Введите контент', null=True, verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pattern',
            field=models.CharField(choices=[('slider_news', 'На слайдере'), ('second_form_news', 'На основной странице')], default='second_form_news', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('draft', 'Не активен'), ('published', 'Активен')], default='draft', max_length=10, verbose_name='Статус на сайте'),
        ),
        migrations.AddField(
            model_name='news',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.city', verbose_name='Местоположение'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название центра', max_length=100, verbose_name='Название')),
                ('address_line', models.CharField(help_text='Введите адрес центра', max_length=255, verbose_name='Адрес')),
                ('phone_line', models.CharField(help_text='Введите контакты (номера для связи)', max_length=255, verbose_name='Контакты')),
                ('email_line', models.CharField(help_text='Введите адрес электронной почты', max_length=255, verbose_name='Почта')),
                ('latitude', models.FloatField(help_text='Введите широту', verbose_name='Широта')),
                ('longitude', models.FloatField(help_text='Введите долготу', verbose_name='Долгота')),
                ('status', models.CharField(choices=[('draft', 'Не активен'), ('published', 'Активен')], default='draft', max_length=10, verbose_name='Статус сервиса')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Сервисный центр',
                'verbose_name_plural': 'Сервисные центры',
                'ordering': ('title',),
            },
        ),
    ]
