# Generated by Django 5.0.4 on 2024-05-24 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0013_city_news_inner_link_alter_news_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание описание')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.RenameField(
            model_name='city',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='phone',
            name='inner_link',
            field=models.URLField(blank=True, verbose_name=''),
        ),
        migrations.CreateModel(
            name='StoreURLField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка на телефон')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='phones.phone')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.store', verbose_name='Пользователи')),
            ],
        ),
    ]
