# Generated by Django 5.0.4 on 2024-05-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0017_alter_phone_inner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='has_download_url',
            field=models.BooleanField(default=False, verbose_name='Есть ссылка на скачивание'),
        ),
    ]
