# Generated by Django 5.0.4 on 2024-05-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0015_alter_storeurlfield_options_alter_photo_color_and_more'),
        ('phones', '0018_phone_has_download_url'),
    ]

    operations = [
    ]
